[package]
name = "rust_final_project"
version = "0.1.0"
edition = "2021"

[dependencies]
actix = "0.13.5"
actix-web = "4.1"
serde = {version = "1.0", features = ["derive"]}
axum = "0.6"
tokio = { version = "1.0", features = ["full"] }